### ISSUE TITLE
How to sample a part of the data for training, verification, and testing?

### ISSUE THREAD

**Issue by wenjie-yuan** [Syniez/SlaBins#1]
![image](https://github.com/Syniez/SlaBins/assets/67451272/fa2eeafa-30c2-45d2-843a-b0ec47e7796b)
The paper does not use the full data of kitti-360, but samples a part of the data for training, verification, and testing. Why is it sampled? Can you share the sampling method and the generated txt file? This will make it easier for others to do comparative experiments.

**Comment by Syniez** [comment]
In the case of SynWoodScape dataset, we used a total of 18K datasets for training (14.4K), validation (1.8K), and testing (1.8K). Although KITTI-360 provides many more dataset sequences than SynWoodScape, we decided to use a similar amount of data as SynWoodScape. (So we used a total 19.2K data)

The reason why we sampled the dataset:
- To make dense lidar GT, we aggregate GT lidar data into specific frames using camera parameters. (described in the paper 4.1) In this process, we saw that neighborhood frames seem very similar. Then, we first sampled the whole sequence into times of 8 frames (e.g, frame number: 0, 8, 16, 24, ...)
- After sampling whole frames, we randomly selected 4K, 0.4K, and 0.4K from the sampled frames for training, validation, and testing. (I will provide the used txt file below)

[dense_train_kitti360.txt](https://github.com/Syniez/SlaBins/files/13246988/dense_train_kitti360.txt)
[dense_val_kitti360.txt](https://github.com/Syniez/SlaBins/files/13246994/dense_val_kitti360.txt)
[dense_test_kitti360.txt](https://github.com/Syniez/SlaBins/files/13246996/dense_test_kitti360.txt)
